name: Update EKS Deployment

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  update-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name bookshop_cluster --region us-east-1

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy updated backend image
        run: |
          helm upgrade backend ./helm/backend-chart \
            --namespace devops-project \
            --set image.repository=mladenovskistefan/backend \
            --set image.tag=latest

      - name: Deploy updated frontend image
        run: |
          helm upgrade frontend ./helm/frontend-chart \
            --namespace devops-project \
            --set image.repository=mladenovskistefan/frontend \
            --set image.tag=latest
